server:
  port: 8080

# Application Configuration
app:
  ai-provider: ${AI_PROVIDER:ollama}  # Options: ollama, openai

spring:
  application:
    name: trms-ai-backend
  
  # Spring AI Configuration
  ai:
    # Ollama Configuration (Primary AI Provider)
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${OLLAMA_MODEL:qwen3:1.7b}
          temperature: 0.3
    
    # OpenAI Configuration (Fallback)
    openai:
      api-key: ${OPENAI_API_KEY:sk-demo-key}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: ${AI_MODEL:gpt-4o-mini}
          temperature: 0.3
          max-tokens: 2000
      
    # Function calling configuration
    chat:
      client:
        options:
          functions:
            - getAccountsByCurrency
            - checkAccountBalance
            - bookTransaction
            - checkEODReadiness
            - proposeRateFixings

# TRMS Legacy System Configuration
trms:
  legacy:
    base-url: http://localhost:8090
    timeout: 30000
    retry-attempts: 3
    retry-delay: 1000

# SWIFT Mock System Configuration
swift-mock:
  base-url: ${SWIFT_MOCK_BASE_URL:http://localhost:8091}

# Logging Configuration
logging:
  level:
    com.trms.ai: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.web: INFO
    org.apache.http: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: logs/trms-ai-backend.log

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      cors:
        allowed-origins: "http://localhost:3000"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-headers: "*"
        allow-credentials: true
  endpoint:
    health:
      show-details: when-authorized

# CORS Configuration
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://127.0.0.1:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  max-age: 3600