server:
  port: 8090
  servlet:
    context-path: /

spring:
  application:
    name: trms-mock-app
  
  # Jackson configuration for JSON processing
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    
  # Web configuration
  web:
    resources:
      static-locations: classpath:/static/
      
  # Actuator configuration
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
        base-path: /actuator
    endpoint:
      health:
        show-details: always
        show-components: always
    health:
      db:
        enabled: false
      diskspace:
        enabled: true
    info:
      env:
        enabled: true
      java:
        enabled: true
      os:
        enabled: true

# Application specific configuration
trms:
  mock:
    name: "TRMS Legacy Mock System"
    version: "1.0.0"
    description: "Mock Treasury and Risk Management System for AI Agent POC"
    environment: "development"

# SWIFT mock integration
swift-mock:
  base-url: ${SWIFT_MOCK_BASE_URL:http://localhost:8091/api/v1/swift}
    
  data:
    initialization:
      enabled: true
      accounts-count: 8
      transactions-count: 4
      
  eod:
    cutoff-time: "17:00"
    timezone: "America/New_York"
    auto-approve-threshold: 10000
    
  api:
    version: "v1"
    rate-limit:
      enabled: false
      requests-per-minute: 1000

# Logging configuration
logging:
  level:
    com.trms.mock: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/trms-mock-app.log

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  show-actuator: true
  
---
# Development profile
spring:
  config:
    activate:
      on-profile: development
      
logging:
  level:
    com.trms.mock: DEBUG
    org.springframework.web: DEBUG
    
trms:
  mock:
    environment: "development"
  data:
    initialization:
      enabled: true

---
# Production profile  
spring:
  config:
    activate:
      on-profile: production
      
logging:
  level:
    com.trms.mock: WARN
    org.springframework.web: WARN
    
trms:
  mock:
    environment: "production"
  api:
    rate-limit:
      enabled: true
      requests-per-minute: 500

---
# Test profile
spring:
  config:
    activate:
      on-profile: test
      
logging:
  level:
    com.trms.mock: TRACE
    
trms:
  mock:
    environment: "test"
  data:
    initialization:
      enabled: false